# Generated by Django 3.1.2 on 2020-12-17 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('type', models.CharField(max_length=50)),
                ('units', models.CharField(max_length=4)),
                ('price', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=550)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
    ]
