# Generated by Django 3.1.2 on 2020-12-21 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_property_street'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('showing', models.CharField(choices=[('M', 'Morning'), ('N', 'Noon'), ('A', 'Afternoon')], default='M', max_length=1)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.property')),
            ],
        ),
    ]
